### ISSUE TITLE
Crashes on Windows permanently

### ISSUE THREAD

**Issue by 0lm** [jfiguinha/Regards#5]
Unfortunately it is stuck in a crash loop on windows, when I tried to add folders with tons of images and videos. I think its especially the amount of videos Regards cant handle. I uninstalled and reinstalled it, but it sitll tried to load that one folder with lots of videos that causes it to crash, i think. But im not sure what exctly causes it to crash tbh. At the satrt i always get "couldnt connect to server" and after a few seconds after that it crashes. (Why does it need internet?)
And also, cold you tell me where the config files are stored? since even after new installation of Regards, it tried to add exactly the same folder. So I need ot location of its config file to reset Regards, so it wont try ot add the same folder anymore.

**Comment by jfiguinha** [comment]
Hi, thanks for your return.
The config files are located in this folder "My Documents/Regards".
You have 4 files : 
- 2 config files : Regards.config and Regards.viewer.config
Regards.config save the Application Configuration.
- 1 theme files
- 1 database file : regards.db. You can open it with dbbrowser.

The application needs internet because it requests the geolocalisation of the file from lat and long to city name.

You can restart Regards after you delete regards.db file.

For your problem, I think there are a problem with a movie file. You can find it with the opening of the regards.db file with this application https://sqlitebrowser.org/. Regards saves the thumbnail of each files. You need just to find the last thumbnail create in PhotosThumbnail table and compare with the file list of Photos Table.

I recommand you to delete Regards.db file to get a clean db files and retry the process with the folder which contains the problematic file. If you find it, I will be interest to get it for debugging my application.

Best Regards

**Comment by jfiguinha** [comment]
Hi,
I just update Regards Viewer. Can you try it and tell me if the application crash again ?
Thanks
Best Regards

**Comment by jfiguinha** [comment]
No response from sender
